### PR TITLE
Fix error on first launch and add the French translation.

### PR DESCRIPTION
**Pull request by Skyy4**
At the first launch, there was an **error**
Screenshot_4

I fixed this error by adding the default "PT" language on first launch.
I took the opportunity to add the French translation.

### First Lauch (fixed)
Screenshot_5
### French translation
Screenshot_6

### CODE REVIEW

**Comment by henriquelbsouza** [comment]
Hi @Skyy4 thanks for your pull request. 

Can you please fix the lint error? 
It is just replace the double quotes with single quotes on the "pt" string. Thank you

I will merge right after =)

**Comment by Skyy4** [comment]
Hi @henriquelbsouza  !
Sorry for the double quotes :x
Now the language is automatically detected among the translations

Thank you for your reply =)

**Comment by henriquelbsouza** [comment]
I was taking a look at the translation, I think you can just fix that part of the code, checking if the user's language is valid (fr, pt, en, es) instead of defaulting to 'pt'... 

https://github.com/gamersclub-booster/gamersclub-booster/blob/dbef6993daf3fc5ebb5def0e2e1a1fdbaebbe980/src/options/index.js#L71-L76 

Also our lint rules are a bit strict as you can see from the build, just to improve/standarize a bit the code. I can help you with that if you need. 

Thanks again and sorry if the code is not that welcoming for first contributors, refactor everything is in my plans...

**Comment by henriquelbsouza** [comment]
Thanks! @Skyy4 

I will merge it now

**Comment by Skyy4** [comment]
Thanks, I edited this part

Normally there should be no error.

The 'pt' translation is chosen if the browser language is not available
=)

**Comment by henriquelbsouza** [comment]
> Thanks, I edited this part
> 
> Normally there should be no error.
> 
> The 'pt' translation is chosen if the browser language is not available =)

Yep, it looks good :) I will test it and publish to the stores later

@all-contributors please add @Skyy4 for code, bug, translation

**Pull request merged**
